profiles:
  2vcpu-8g:
    cpus: 2
    memory: "8G"
tdx:
  acpi_distribution: "ubuntu:26.04"
  qemu_source_version: "11.0.1"
  qemu:
    measurement_machine: "q35,kernel-irqchip=split,hpet=off,smm=off,pic=off"
    runtime_machine: "q35,kernel-irqchip=split,hpet=off,smm=off,pic=off,confidential-guest-support=tdx"
    cpu: "host,pmu=off"
    accel: "kvm"
    measurement_objects: []
    runtime_objects:
      - "tdx-guest,id=tdx"
    netdevs:
      - "user,id=network0"
    measurement_netdevs:
      - "hubport,id=network0,hubid=0"
    measurement_devices:
      - "virtio-serial-pci,id=serial0,disable-modern=false,max_ports=2"
      - "virtconsole,chardev=charconsole0"
      - "virtio-blk-pci,drive=root,disable-modern=false"
      - "virtio-scsi-pci,id=scsi0,disable-modern=false"
      - "virtio-net-pci,netdev=network0,disable-modern=false,romfile="
      - "vhost-vsock-pci,guest-cid=3,disable-modern=false"
    runtime_devices:
      - "virtio-serial-pci,id=serial0,disable-modern=false,max_ports=2"
      - "virtconsole,chardev=charconsole0"
      - "virtio-blk-pci,drive=root,disable-modern=false"
      - "virtio-scsi-pci,id=scsi0,disable-modern=false"
      - "virtio-net-pci,netdev=network0,disable-modern=false"
      - "vhost-vsock-pci,guest-cid=3,disable-modern=false"
sev:
  defaults:
    vcpu_types:
      - "EPYC-v4"
      - "EPYC-Milan-v2"
      - "EPYC-Genoa-v1"
      - "EPYC-Turin"
    vmm_type: "QEMU"
    guest_features: "0x1"
  qemu:
    machine: "q35,vmport=off,confidential-guest-support=sev0,memory-backend=ram1"
    memory_backend:
      id: "ram1"
      share: true
      prealloc: false
    guest:
      id: "sev0"
      cbitpos: 51
      reduced_phys_bits: 1
      kernel_hashes: true
    netdevs:
      - "user,id=network0"
    runtime_devices:
      - "virtio-serial-pci,id=serial0,disable-modern=false,max_ports=2"
      - "virtconsole,chardev=charconsole0"
      - "virtio-blk-pci,drive=root,disable-modern=false"
      - "virtio-scsi-pci,id=scsi0,disable-modern=false"
      - "virtio-net-pci,netdev=network0,disable-modern=false"
      - "vhost-vsock-pci,guest-cid=3,disable-modern=false"
